server:
  port: 8001
  context-path: /sell
spring:
  profiles:
    active:
      - default
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/sell?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    druid:
      validation-query: SELECT 1
      initial-size: 2                                     # 初始化连接数
      min-idle: 2                                         # 最小连接数
      max-active: 8                                       # 最大连接数
      max-wait: 60000                                     # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper                     # 指定mapper接口父类
pagehelper:
  helper-dialect: mysql
  params: count=countSql
logging:
  level:
    cn.colg.mapper: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: debug
    
---
server:
  port: 8002
spring:
  profiles: dev